export const SHOW_NEW_CONNECTION_MODAL = 'SHOW_NEW_CONNECTION_MODAL';
export const HIDE_NEW_CONNECTION_MODAL = 'HIDE_NEW_CONNECTION_MODAL';

export const SHOW_URLS_MODAL = 'SHOW_URLS_MODAL';
export const HIDE_URLS_MODAL = 'HIDE_URLS_MODAL';

export const SHOW_TORRENTS_MODAL = 'SHOW_TORRENTS_MODAL';
export const HIDE_TORRENTS_MODAL = 'HIDE_TORRENTS_MODAL';

export const SHOW_METALINKS_MODAL = 'SHOW_METALINKS_MODAL';
export const HIDE_METALINKS_MODAL = 'HIDE_METALINKS_MODAL';
